// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"
)

type Session struct {
	// refresh token id
	ID []byte `json:"id"`
	// refresh token
	RefreshToken string `json:"refresh_token"`
	// access token id
	AccessTokenID []byte `json:"access_token_id"`
	// short lived access token
	AccessToken string `json:"access_token"`
	// client ip address
	ClientIp string `json:"client_ip"`
	// client user agent
	UserAgent string `json:"user_agent"`
	// id of the user assigned to this session
	UserID []byte `json:"user_id"`
	// session is blocked or not
	Blocked bool `json:"blocked"`
	// expiration time of access token
	AccessTokenExpiresAt time.Time `json:"access_token_expires_at"`
	// expiration time of a refresh token
	RefreshTokenExpiresAt time.Time `json:"refresh_token_expires_at"`
	// created at timestamp of this session
	CreatedAt time.Time `json:"created_at"`
	// last updated at timestamp of this session
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	// account id
	ID []byte `json:"id"`
	// unique email address
	Email string `json:"email"`
	// unique username
	Username string `json:"username"`
	// salt used for hashing
	HashSalt string `json:"hash_salt"`
	// hashed password
	HashPass string `json:"hash_pass"`
	// first name
	Firstname string `json:"firstname"`
	// last name
	Lastname string `json:"lastname"`
	// email verified status
	Verified bool `json:"verified"`
	// account blocked status
	Blocked bool `json:"blocked"`
	// created at timestamp
	CreatedAt time.Time `json:"created_at"`
	// last updated at timestamp
	UpdatedAt time.Time `json:"updated_at"`
	// email verification token
	TokenEmailVerify string `json:"token_email_verify"`
	// password reset token
	TokenPasswordReset string `json:"token_password_reset"`
	// email change token
	TokenEmailChange string `json:"token_email_change"`
	// user deletion token
	TokenUserDeletion string `json:"token_user_deletion"`
	// last email verification timestamp
	LastEmailVerify time.Time `json:"last_email_verify"`
	// last password reset timestamp
	LastPasswordReset time.Time `json:"last_password_reset"`
	// last email change timestamp
	LastEmailChange time.Time `json:"last_email_change"`
	// last user deletion timestamp
	LastUserDeletion time.Time `json:"last_user_deletion"`
}
