// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id []byte) error
	ReadUser(ctx context.Context, id []byte) (User, error)
	ReadUserByEmail(ctx context.Context, email string) (User, error)
	ReadUserByUsername(ctx context.Context, username string) (User, error)
	ReadUsers(ctx context.Context, arg ReadUsersParams) ([]User, error)
	UpdateUserDeletionToken(ctx context.Context, arg UpdateUserDeletionTokenParams) error
	UpdateUserEmailVerificationToken(ctx context.Context, arg UpdateUserEmailVerificationTokenParams) error
	UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPasswordResetToken(ctx context.Context, arg UpdateUserPasswordResetTokenParams) error
}

var _ Querier = (*Queries)(nil)
