---
project_name: trueauth

builds:
  - id: linux-amd64
    binary: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    goos:
      - linux
    goarch:
      - amd64
    no_unique_dist_dir: true
    hooks:
      post:
        - cp -f defaults.env dist

  - id: darwin-amd64
    binary: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    goos:
      - darwin
    goarch:
      - amd64
    no_unique_dist_dir: true
    hooks:
      post:
        - cp -f defaults.env dist

  - id: windows-amd64
    binary: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    goos:
      - windows
    goarch:
      - amd64
    no_unique_dist_dir: true
    hooks:
      post:
        - cp -f defaults.env dist

archives:
  - format: tar.xz
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    files:
      - defaults.env

checksum:
  name_template: "{{.ProjectName}}_checksums.txt"
