---
version: "3.8"

volumes:
  trueauth-redis:
  trueauth-postgres:

networks:
  trueauth:
  proxy:
    external: true

services:

  trueauth-postgres:
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    container_name: trueauth-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - trueauth-postgres:/var/lib/postgresql/data
    networks: [trueauth]

  trueauth-redis:
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    container_name: trueauth-redis
    image: redis:alpine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - trueauth-redis:/data
    networks: [trueauth]


  trueauth-haproxy:
    image: haproxy:lts-alpine
    container_name: trueauth-haproxy
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on: [trueauth]
    ports: 
      - 4420:80  # Http port
      - 4421:50051  # Grpc port
    networks: [proxy]

  trueauth:
    security_opt: [no-new-privileges:true]
    build:
      context: .
    restart: unless-stopped
    command: ["/app/main"]
    entrypoint: ["/app/wait-for.sh", "trueauth-postgres:5432", "--", "/app/start.sh"]
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on: [trueauth-postgres, trueauth-redis]
    networks: [trueauth, proxy]
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
