version: '3'

volumes:
  trueauth_db:
  trueauth_redis:

services:
  trueauth_redis:
    container_name: trueauth_redis
    image: redis:latest
    volumes:
      - trueauth_redis:/data

  trueauth_db:
    container_name: trueauth_db
    image: postgres:14-alpine
    volumes:
      - trueauth_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  trueauth:
    container_name: trueauth
    image: ghcr.io/sirjager/trueauth:latest
    depends_on:
      - trueauth_db
      - trueauth_redis
    ports:
      - 4420
      - 4421
    environment:
      - DB_HOST=trueauth_db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DRIVER=postgres
      - DB_ARGS=?sslmode=disable
      - DB_MIGRATE=./migrations
      - GMAIL_NAME=${GMAIL_NAME}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
      - REDIS_ADDR=trueauth_redis:6379
    entrypoint: ['/app/wait-for.sh', 'trueauth_db:5432', '--', '/app/start.sh']
    command: ['/app/main']
