---
version: "3.8"

volumes:
  trueauth-pg:
  trueauth-redis:

networks:
  trueauth:
  proxy:
    external: true

services:

  postgres:
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    container_name: trueauth-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - trueauth-pg:/var/lib/postgresql/data
    networks:
      - trueauth
    ports: [5432:5432]  # Disable ports in production

  redis:
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    container_name: trueauth-redis
    image: redis:alpine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - trueauth-redis:/data
    networks:
      - trueauth
    ports: [6379:6379]   # Disable ports in production

  # goapp:
  #   security_opt: [no-new-privileges:true]
  #   build:
  #     context: .
  #   restart: unless-stopped
  #   command: ["/app/main"]
  #   entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
  #   environment:
  #     DATABASE_HOST: postgres
  #     REDIS_ADDRESS: redis:6379
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - trueauth-proxy
  #   deploy:
  #     replicas: 3
  #     resources:
  #       limits:
  #         memory: 256M

  # nginx:
  #   <<: *x-logging
  #   security_opt: [no-new-privileges:true]
  #   container_name: trueauth-nginx
  #   restart: unless-stopped
  #   image: nginx
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - trueauth-proxy
  #     - proxy
  #   depends_on:
  #     - goapp
  #   # ports:
  #     # - 4420:80  # disable in production
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: 256M
