version: '3'

volumes:
  trueauthdb:

services:
  trueauthdb:
    container_name: trueauthdb
    image: postgres:14-alpine
    volumes:
      - trueauthdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  trueauth:
    image: ghcr.io/sirjager/trueauth:latest
    container_name: trueauth
    depends_on:
      - trueauthdb
    ports:
      - 4420
      - 4424
    environment:
      - DB_HOST=trueauthdb
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DRIVER=postgres
      - DB_ARGS=?sslmode=disable
      - DB_MIGRATE=./migrations
      - GMAIL_NAME=${GMAIL_NAME}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
    entrypoint: ['/app/wait-for.sh', 'trueauthdb:5432', '--', '/app/start.sh']
    command: ['/app/main']
