---
version: "3.8"

volumes:
  trueauth-pg:
  trueauth-redis:

networks:
  trueauth:
  proxy:
    external: true

services:

  postgres:
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    container_name: trueauth-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - trueauth-pg:/var/lib/postgresql/data
    networks: [trueauth]
    # ports: [5432:5432]  # Disable ports in production

  redis:
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    container_name: trueauth-redis
    image: redis:alpine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - trueauth-redis:/data
    networks: [trueauth]
    # ports: [6379:6379]   # Disable ports in production


  haproxy:
    image: haproxy:lts-alpine
    container_name: trueauth
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on: [trueauth]
    ports: 
      - 4420:80  # Http port
      - 4421:50051  # Grpc port
    networks: [proxy]

  trueauth:
    security_opt: [no-new-privileges:true]
    build:
      context: .
    restart: unless-stopped
    command: ["/app/main"]
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    environment:
      REDIS_ADDRESS: redis:6379
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on: [postgres, redis]
    networks: [trueauth, proxy]
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 256M
