---
version: "3.8"

x-logging: &x-logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

volumes:
  trueauth-pg:
  trueauth-redis:

networks:
  trueauth-proxy:
  proxy:
    external: true

services:
  # ---

  postgres:
    <<: *x-logging
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    container_name: trueauth-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - trueauth-pg:/var/lib/postgresql/data
    networks:
      - trueauth-proxy
    ports: [5432:5432]  # Disable ports in production

  redis:
    <<: *x-logging
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    container_name: trueauth-redis
    image: redis:alpine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - trueauth-redis:/data
    networks:
      - trueauth-proxy
    ports: [6381:6379]   # Disable ports in production

  # trueauth:
  #   <<: *x-logging
  #   security_opt: [no-new-privileges:true]
  #   build:
  #     context: .
  #   restart: unless-stopped
  #   command: ["/app/main"]
  #   entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
  #   environment:
  #     DATABASE_HOST: postgres
  #     REDIS_ADDRESS: redis:6379
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - trueauth-proxy
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         memory: 256M

  # nginx:
  #   <<: *x-logging
  #   security_opt: [no-new-privileges:true]
  #   container_name: trueauth-nginx
  #   restart: unless-stopped
  #   image: nginx
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - trueauth-proxy
  #     - proxy
  #   depends_on:
  #     - trueauth
  #   ports:
  #     - 4420:80
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: 256M
