// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"time"
)

type User struct {
	// user id
	ID []byte `json:"id"`
	// unique email address
	Email string `json:"email"`
	// unique username
	Username string `json:"username"`
	// hashed password
	Password string `json:"password"`
	// first name
	Firstname string `json:"firstname"`
	// last name
	Lastname string `json:"lastname"`
	// email verified status
	EmailVerified bool `json:"email_verified"`
	// list of all allowed ip address to access this row
	AllowedIps []string `json:"allowed_ips"`
	// created at timestamp
	CreatedAt time.Time `json:"created_at"`
	// last updated at timestamp
	UpdatedAt time.Time `json:"updated_at"`
}
