// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	ReadSessionByAccessTokenID(ctx context.Context, accessTokenID uuid.UUID) (Session, error)
	ReadSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	ReadSessionsByUserID(ctx context.Context, arg ReadSessionsByUserIDParams) ([]Session, error)
	ReadUserByEmail(ctx context.Context, email string) (User, error)
	ReadUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ReadUserByUsername(ctx context.Context, username string) (User, error)
	ReadUsers(ctx context.Context, arg ReadUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAllowIP(ctx context.Context, arg UpdateUserAllowIPParams) error
	UpdateUserAllowIPToken(ctx context.Context, arg UpdateUserAllowIPTokenParams) error
	UpdateUserDeleteToken(ctx context.Context, arg UpdateUserDeleteTokenParams) error
	UpdateUserEmailChangeToken(ctx context.Context, arg UpdateUserEmailChangeTokenParams) error
	UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) error
	UpdateUserRecoveryToken(ctx context.Context, arg UpdateUserRecoveryTokenParams) error
	UpdateUserResetPassword(ctx context.Context, arg UpdateUserResetPasswordParams) error
	UpdateUserVerifyToken(ctx context.Context, arg UpdateUserVerifyTokenParams) error
}

var _ Querier = (*Queries)(nil)
