// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id []byte) error
	ReadUserByEmail(ctx context.Context, email string) (User, error)
	ReadUserByID(ctx context.Context, id []byte) (User, error)
	ReadUserByIdentity(ctx context.Context, arg ReadUserByIdentityParams) (User, error)
	ReadUserByUsername(ctx context.Context, username string) (User, error)
	ReadUsers(ctx context.Context, arg ReadUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
