// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, username, password, email_verified, firstname, lastname, allowed_ips) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, email, username, password, firstname, lastname, email_verified, allowed_ips, created_at, updated_at
`

type CreateUserParams struct {
	ID            []byte   `json:"id"`
	Email         string   `json:"email"`
	Username      string   `json:"username"`
	Password      string   `json:"password"`
	EmailVerified bool     `json:"email_verified"`
	Firstname     string   `json:"firstname"`
	Lastname      string   `json:"lastname"`
	AllowedIps    []string `json:"allowed_ips"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.EmailVerified,
		arg.Firstname,
		arg.Lastname,
		pq.Array(arg.AllowedIps),
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.EmailVerified,
		pq.Array(&i.AllowedIps),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const readUserByEmail = `-- name: ReadUserByEmail :one
SELECT id, email, username, password, firstname, lastname, email_verified, allowed_ips, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) ReadUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, readUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.EmailVerified,
		pq.Array(&i.AllowedIps),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readUserByID = `-- name: ReadUserByID :one
SELECT id, email, username, password, firstname, lastname, email_verified, allowed_ips, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) ReadUserByID(ctx context.Context, id []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, readUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.EmailVerified,
		pq.Array(&i.AllowedIps),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readUserByIdentity = `-- name: ReadUserByIdentity :one
SELECT id, email, username, password, firstname, lastname, email_verified, allowed_ips, created_at, updated_at FROM users WHERE email = $1 OR username = $2 LIMIT 1
`

type ReadUserByIdentityParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) ReadUserByIdentity(ctx context.Context, arg ReadUserByIdentityParams) (User, error) {
	row := q.db.QueryRowContext(ctx, readUserByIdentity, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.EmailVerified,
		pq.Array(&i.AllowedIps),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readUserByUsername = `-- name: ReadUserByUsername :one
SELECT id, email, username, password, firstname, lastname, email_verified, allowed_ips, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) ReadUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, readUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.EmailVerified,
		pq.Array(&i.AllowedIps),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const readUsers = `-- name: ReadUsers :many
SELECT id, email, username, password, firstname, lastname, email_verified, allowed_ips, created_at, updated_at FROM users LIMIT $2 OFFSET $1
`

type ReadUsersParams struct {
	Offset sql.NullInt32 `json:"offset"`
	Limit  sql.NullInt32 `json:"limit"`
}

func (q *Queries) ReadUsers(ctx context.Context, arg ReadUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, readUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.Firstname,
			&i.Lastname,
			&i.EmailVerified,
			pq.Array(&i.AllowedIps),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    email = $1,
    username = $2,
    password = $3,
    firstname = $4,
    lastname = $5
WHERE id = $6 RETURNING id, email, username, password, firstname, lastname, email_verified, allowed_ips, created_at, updated_at
`

type UpdateUserParams struct {
	Email     string `json:"email"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	ID        []byte `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Firstname,
		arg.Lastname,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.EmailVerified,
		pq.Array(&i.AllowedIps),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
