// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: emailentries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailEntry = `-- name: CreateEmailEntry :one
INSERT INTO emailentries (
    email, user_id, verified, code, code_expires_at
) VALUES ($1, $2, $3, $4, $5) RETURNING id, email, user_id, verified, code, code_expires_at, created_at, updated_at
`

type CreateEmailEntryParams struct {
	Email         string    `json:"email"`
	UserID        uuid.UUID `json:"user_id"`
	Verified      bool      `json:"verified"`
	Code          string    `json:"code"`
	CodeExpiresAt time.Time `json:"code_expires_at"`
}

func (q *Queries) CreateEmailEntry(ctx context.Context, arg CreateEmailEntryParams) (Emailentry, error) {
	row := q.db.QueryRowContext(ctx, createEmailEntry,
		arg.Email,
		arg.UserID,
		arg.Verified,
		arg.Code,
		arg.CodeExpiresAt,
	)
	var i Emailentry
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.Verified,
		&i.Code,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailEntry = `-- name: GetEmailEntry :one
SELECT id, email, user_id, verified, code, code_expires_at, created_at, updated_at FROM emailentries WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmailEntry(ctx context.Context, id uuid.UUID) (Emailentry, error) {
	row := q.db.QueryRowContext(ctx, getEmailEntry, id)
	var i Emailentry
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.Verified,
		&i.Code,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmailEntry = `-- name: UpdateEmailEntry :one
UPDATE emailentries SET
 verified = $1,
 code = $2,
 code_expires_at = $3
WHERE id = $4 RETURNING id, email, user_id, verified, code, code_expires_at, created_at, updated_at
`

type UpdateEmailEntryParams struct {
	Verified      bool      `json:"verified"`
	Code          string    `json:"code"`
	CodeExpiresAt time.Time `json:"code_expires_at"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateEmailEntry(ctx context.Context, arg UpdateEmailEntryParams) (Emailentry, error) {
	row := q.db.QueryRowContext(ctx, updateEmailEntry,
		arg.Verified,
		arg.Code,
		arg.CodeExpiresAt,
		arg.ID,
	)
	var i Emailentry
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.Verified,
		&i.Code,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
