// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: emails.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (email,verified,token,last_token_sent_at) VALUES ($1, $2, $3, $4) RETURNING id, email, verified, token, last_token_sent_at, created_at, updated_at
`

type CreateEmailParams struct {
	Email           string    `json:"email"`
	Verified        bool      `json:"verified"`
	Token           string    `json:"token"`
	LastTokenSentAt time.Time `json:"last_token_sent_at"`
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error) {
	row := q.db.QueryRowContext(ctx, createEmail,
		arg.Email,
		arg.Verified,
		arg.Token,
		arg.LastTokenSentAt,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Verified,
		&i.Token,
		&i.LastTokenSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailByEmail = `-- name: GetEmailByEmail :one
SELECT id, email, verified, token, last_token_sent_at, created_at, updated_at FROM emails WHERE email = $1 LIMIT 1
`

func (q *Queries) GetEmailByEmail(ctx context.Context, email string) (Email, error) {
	row := q.db.QueryRowContext(ctx, getEmailByEmail, email)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Verified,
		&i.Token,
		&i.LastTokenSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailByID = `-- name: GetEmailByID :one
SELECT id, email, verified, token, last_token_sent_at, created_at, updated_at FROM emails WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmailByID(ctx context.Context, id uuid.UUID) (Email, error) {
	row := q.db.QueryRowContext(ctx, getEmailByID, id)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Verified,
		&i.Token,
		&i.LastTokenSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmail = `-- name: UpdateEmail :one
UPDATE emails SET
 verified = $1,
 token = $2,
 last_token_sent_at = $3
WHERE id = $4 RETURNING id, email, verified, token, last_token_sent_at, created_at, updated_at
`

type UpdateEmailParams struct {
	Verified        bool      `json:"verified"`
	Token           string    `json:"token"`
	LastTokenSentAt time.Time `json:"last_token_sent_at"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) (Email, error) {
	row := q.db.QueryRowContext(ctx, updateEmail,
		arg.Verified,
		arg.Token,
		arg.LastTokenSentAt,
		arg.ID,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Verified,
		&i.Token,
		&i.LastTokenSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
