// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: iprecords.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createIPRecord = `-- name: CreateIPRecord :exec
INSERT INTO iprecords (id, allowed_ips, blocked_ips, code, code_expires_at) VALUES ($1, $2, $3, $4, $5)
`

type CreateIPRecordParams struct {
	ID            uuid.UUID `json:"id"`
	AllowedIps    []string  `json:"allowed_ips"`
	BlockedIps    []string  `json:"blocked_ips"`
	Code          string    `json:"code"`
	CodeExpiresAt time.Time `json:"code_expires_at"`
}

func (q *Queries) CreateIPRecord(ctx context.Context, arg CreateIPRecordParams) error {
	_, err := q.db.ExecContext(ctx, createIPRecord,
		arg.ID,
		pq.Array(arg.AllowedIps),
		pq.Array(arg.BlockedIps),
		arg.Code,
		arg.CodeExpiresAt,
	)
	return err
}

const getIPRecord = `-- name: GetIPRecord :one
SELECT id, allowed_ips, blocked_ips, code, code_expires_at, created_at, updated_at FROM iprecords WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIPRecord(ctx context.Context, id uuid.UUID) (Iprecord, error) {
	row := q.db.QueryRowContext(ctx, getIPRecord, id)
	var i Iprecord
	err := row.Scan(
		&i.ID,
		pq.Array(&i.AllowedIps),
		pq.Array(&i.BlockedIps),
		&i.Code,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIPRecord = `-- name: UpdateIPRecord :one
UPDATE iprecords SET
 allowed_ips = $1,
 blocked_ips = $2,
 code = $3,
 code_expires_at = $4
WHERE id = $5 RETURNING id, allowed_ips, blocked_ips, code, code_expires_at, created_at, updated_at
`

type UpdateIPRecordParams struct {
	AllowedIps    []string  `json:"allowed_ips"`
	BlockedIps    []string  `json:"blocked_ips"`
	Code          string    `json:"code"`
	CodeExpiresAt time.Time `json:"code_expires_at"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateIPRecord(ctx context.Context, arg UpdateIPRecordParams) (Iprecord, error) {
	row := q.db.QueryRowContext(ctx, updateIPRecord,
		pq.Array(arg.AllowedIps),
		pq.Array(arg.BlockedIps),
		arg.Code,
		arg.CodeExpiresAt,
		arg.ID,
	)
	var i Iprecord
	err := row.Scan(
		&i.ID,
		pq.Array(&i.AllowedIps),
		pq.Array(&i.BlockedIps),
		&i.Code,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
