// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionByAccount(ctx context.Context, accountID uuid.UUID) error
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByUsername(ctx context.Context, username string) (Account, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByAccessTokenID(ctx context.Context, accessTokenID uuid.UUID) (Session, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListSessionsByAccount(ctx context.Context, arg ListSessionsByAccountParams) ([]Session, error)
	UpdateAccountAllowIP(ctx context.Context, arg UpdateAccountAllowIPParams) error
	UpdateAccountAllowIPToken(ctx context.Context, arg UpdateAccountAllowIPTokenParams) error
	UpdateAccountEmail(ctx context.Context, arg UpdateAccountEmailParams) error
	UpdateAccountEmailChangeToken(ctx context.Context, arg UpdateAccountEmailChangeTokenParams) error
	UpdateAccountEmailConfirmationToken(ctx context.Context, arg UpdateAccountEmailConfirmationTokenParams) error
	UpdateAccountEmailVerified(ctx context.Context, arg UpdateAccountEmailVerifiedParams) error
	UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error
	UpdateAccountRecoveryToken(ctx context.Context, arg UpdateAccountRecoveryTokenParams) error
}

var _ Querier = (*Queries)(nil)
