// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Create_Session(ctx context.Context, arg Create_SessionParams) (Session, error)
	Create_User(ctx context.Context, arg Create_UserParams) (User, error)
	Delete_Session(ctx context.Context, id uuid.UUID) error
	Delete_Session_ByUserID(ctx context.Context, userID uuid.UUID) error
	Delete_User(ctx context.Context, id uuid.UUID) error
	Read_Session_ByAccessTokenID(ctx context.Context, accessTokenID uuid.UUID) (Session, error)
	Read_Session_ByID(ctx context.Context, id uuid.UUID) (Session, error)
	Read_Sessions_ByUserID(ctx context.Context, arg Read_Sessions_ByUserIDParams) ([]Session, error)
	Read_User_ByEmail(ctx context.Context, email string) (User, error)
	Read_User_ByID(ctx context.Context, id uuid.UUID) (User, error)
	Read_User_ByUsername(ctx context.Context, username string) (User, error)
	Read_Users(ctx context.Context, arg Read_UsersParams) ([]User, error)
	Update_User(ctx context.Context, arg Update_UserParams) (User, error)
	Update_User_AllowIP(ctx context.Context, arg Update_User_AllowIPParams) error
	Update_User_AllowIPToken(ctx context.Context, arg Update_User_AllowIPTokenParams) error
	Update_User_DeleteToken(ctx context.Context, arg Update_User_DeleteTokenParams) error
	Update_User_EmailChangeToken(ctx context.Context, arg Update_User_EmailChangeTokenParams) error
	Update_User_EmailVerified(ctx context.Context, arg Update_User_EmailVerifiedParams) error
	Update_User_RecoveryToken(ctx context.Context, arg Update_User_RecoveryTokenParams) error
	Update_User_ResetPassword(ctx context.Context, arg Update_User_ResetPasswordParams) error
	Update_User_VerifyToken(ctx context.Context, arg Update_User_VerifyTokenParams) error
}

var _ Querier = (*Queries)(nil)
