// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const create_Session = `-- name: Create_Session :one
INSERT INTO sessions (
    id, refresh_token, access_token_id, access_token, user_id, client_ip, user_agent,
    blocked, access_token_expires_at, refresh_token_expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, refresh_token, access_token_id, access_token, client_ip, user_agent, user_id, blocked, access_token_expires_at, refresh_token_expires_at, created_at, updated_at
`

type Create_SessionParams struct {
	ID                    uuid.UUID `json:"id"`
	RefreshToken          string    `json:"refresh_token"`
	AccessTokenID         uuid.UUID `json:"access_token_id"`
	AccessToken           string    `json:"access_token"`
	UserID                uuid.UUID `json:"user_id"`
	ClientIp              string    `json:"client_ip"`
	UserAgent             string    `json:"user_agent"`
	Blocked               bool      `json:"blocked"`
	AccessTokenExpiresAt  time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt time.Time `json:"refresh_token_expires_at"`
}

func (q *Queries) Create_Session(ctx context.Context, arg Create_SessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, create_Session,
		arg.ID,
		arg.RefreshToken,
		arg.AccessTokenID,
		arg.AccessToken,
		arg.UserID,
		arg.ClientIp,
		arg.UserAgent,
		arg.Blocked,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.AccessTokenID,
		&i.AccessToken,
		&i.ClientIp,
		&i.UserAgent,
		&i.UserID,
		&i.Blocked,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete_Session = `-- name: Delete_Session :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) Delete_Session(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete_Session, id)
	return err
}

const delete_Session_ByUserID = `-- name: Delete_Session_ByUserID :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) Delete_Session_ByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete_Session_ByUserID, userID)
	return err
}

const read_Session_ByAccessTokenID = `-- name: Read_Session_ByAccessTokenID :one
SELECT id, refresh_token, access_token_id, access_token, client_ip, user_agent, user_id, blocked, access_token_expires_at, refresh_token_expires_at, created_at, updated_at FROM sessions WHERE access_token_id = $1 LIMIT 1
`

func (q *Queries) Read_Session_ByAccessTokenID(ctx context.Context, accessTokenID uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, read_Session_ByAccessTokenID, accessTokenID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.AccessTokenID,
		&i.AccessToken,
		&i.ClientIp,
		&i.UserAgent,
		&i.UserID,
		&i.Blocked,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const read_Session_ByID = `-- name: Read_Session_ByID :one
SELECT id, refresh_token, access_token_id, access_token, client_ip, user_agent, user_id, blocked, access_token_expires_at, refresh_token_expires_at, created_at, updated_at FROM sessions WHERE id = $1 LIMIT 1
`

func (q *Queries) Read_Session_ByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, read_Session_ByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.AccessTokenID,
		&i.AccessToken,
		&i.ClientIp,
		&i.UserAgent,
		&i.UserID,
		&i.Blocked,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const read_Sessions_ByUserID = `-- name: Read_Sessions_ByUserID :many
SELECT id, refresh_token, access_token_id, access_token, client_ip, user_agent, user_id, blocked, access_token_expires_at, refresh_token_expires_at, created_at, updated_at FROM sessions WHERE user_id = $1 LIMIT $3 OFFSET $2
`

type Read_Sessions_ByUserIDParams struct {
	UserID uuid.UUID     `json:"user_id"`
	Offset sql.NullInt32 `json:"offset"`
	Limit  sql.NullInt32 `json:"limit"`
}

func (q *Queries) Read_Sessions_ByUserID(ctx context.Context, arg Read_Sessions_ByUserIDParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, read_Sessions_ByUserID, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.RefreshToken,
			&i.AccessTokenID,
			&i.AccessToken,
			&i.ClientIp,
			&i.UserAgent,
			&i.UserID,
			&i.Blocked,
			&i.AccessTokenExpiresAt,
			&i.RefreshTokenExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
