Project trueauth {
    database_type: 'PostgreSQL'
    Note: '''
    # TrueAuth Database
    '''
}



Table users as U {
  id uuid [pk, not null, note: 'user id']
  email VARCHAR(255) [unique, not null, note: 'unique email']
  username VARCHAR(255) [unique, not null, note: 'unique username']
  password VARCHAR(255) [not null, note: 'hashed password']
  firstname VARCHAR(255) [default: '', not null, note: 'first name can be empty']
  lastname VARCHAR(255) [default:'', not null, note: 'last name can be empty']
  verified BOOL [not null, default: false, note: 'email verified or not']
  blocked BOOL [not null, default: false, note: 'user blocked or not']
  created_at TIMESTAMPTZ [not null, default: 'now()', note:'created at timestamp']
  updated_at TIMESTAMPTZ [not null, default: 'now()', note: 'last updated at timestamp']

  Indexes {
    firstname
    lastname
  }
}

