package service

import (
	"context"
	"fmt"
	"strings"

	"google.golang.org/genproto/googleapis/rpc/errdetails"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/go-redis/redis/v8"
	rpc "github.com/sirjager/trueauth/stubs/go"
)

func (s *CoreService) Logout(ctx context.Context, req *rpc.LogoutRequest) (*rpc.LogoutResponse, error) {
	if violations := validateLogoutRequest(req); violations != nil {
		return nil, invalidArgumentsError(violations)
	}
	authorized, err := s.authorize(ctx)
	if err != nil {
		return nil, unAuthenticatedError(err)
	}

	sessionIDS := strings.Split(req.GetSessions(), ",")
	commands := []redis.Cmder{}

	count := 0
	if req.GetSessions() != "" && len(sessionIDS) > 0 {
		// if multiple session provided, targeting those sessions
		for _, sessionID := range sessionIDS {
			accessTokenKey := accessTokenKey(string(authorized.user.ID), sessionID)
			refreshTokenKey := refreshTokenKey(string(authorized.user.ID), sessionID)

			commands = append(commands, redis.NewStringCmd(ctx, "DEL", accessTokenKey))
			commands = append(commands, redis.NewStringCmd(ctx, "DEL", refreshTokenKey))
			count += 1
		}
	} else {
		allkeys, err := s.redis.GetKeysWithPrefix(ctx, userSessionsKey(string(authorized.user.ID)))
		if err != nil {
			return nil, status.Errorf(codes.Internal, err.Error())
		}
		for _, delkey := range allkeys {
			commands = append(commands, redis.NewStringCmd(ctx, "DEL", delkey))
			count += 1
		}
	}

	_, err = s.redis.Transaction(ctx, commands)
	if err != nil {
		return nil, status.Errorf(codes.Internal, err.Error())
	}

	return &rpc.LogoutResponse{Message: fmt.Sprintf("signed out from %d sessions", count)}, nil
}

func validateLogoutRequest(req *rpc.LogoutRequest) (violations []*errdetails.BadRequest_FieldViolation) {
	// if no session provided then we simple return
	if req.GetSessions() == "" {
		return
	}
	sessionIDS := strings.Split(req.GetSessions(), ",")
	for index, sessionID := range sessionIDS {
		if len(sessionID) != 20 {
			// our code is always unqiue 20char long generated by utils.UUID_XID()
			violations = append(violations, fieldViolation("sessions", fmt.Errorf("%s is not a valid session id at index %d", sessionID, index+1)))
		}
	}
	return
}

func userSessionsKey(userid string) string {
	return fmt.Sprintf("sessions:%s:*", userid)
}
