package service

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/go-redis/redis/v8"
	"github.com/hibiken/asynq"
	"github.com/lib/pq"

	"google.golang.org/genproto/googleapis/rpc/errdetails"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/sirjager/trueauth/internal/worker"
	"github.com/sirjager/trueauth/pkg/utils"
	"github.com/sirjager/trueauth/pkg/validator"
	rpc "github.com/sirjager/trueauth/stubs/go"
)

func (s *CoreService) Verify(ctx context.Context, req *rpc.VerifyRequest) (*rpc.VerifyResponse, error) {
	violations := validateVerifyRequest(req)
	if violations != nil {
		return nil, invalidArgumentsError(violations)
	}
	// fetch pending registration
	bytes, err := s.redis.Get(ctx, utils.PendingRegistrationKey(req.GetEmail()))
	if err != nil {
		if err == redis.Nil {
			return nil, status.Error(codes.Internal, "invalid email verification code")
		}
		return nil, status.Error(codes.Internal, err.Error())
	}

	var payload worker.PayloadSendEmailVerification
	if err = json.Unmarshal(bytes, &payload); err != nil {
		return nil, status.Error(codes.Internal, err.Error())
	}

	// check if code is same or not
	if payload.VerificationCode != req.GetCode() {
		return nil, status.Error(codes.Internal, "invalid verification code")
	}

	createUserParams := payload.CreateUserParams
	createUserParams.EmailVerified = true
	user, err := s.store.CreateUser(ctx, createUserParams)
	if err != nil {
		if pqErr, ok := err.(*pq.Error); ok {
			switch pqErr.Code.Name() {
			case "unique_violation":
				return nil, status.Errorf(codes.Internal, fmt.Sprintf("%s already exists", unique_violation(pqErr)))
			}
		}
		return nil, status.Errorf(codes.Internal, err.Error())
	}

	// now since user is created we will delete pending registration record from redis
	delOpts := []asynq.Option{asynq.MaxRetry(5), asynq.Group(worker.QUEUE_DEFAULT), asynq.ProcessIn(time.Millisecond)}
	if err = s.taskDistributor.DistributeTaskClearCompletedVerifications(ctx, worker.PayloadClearCompletedVerfications{Email: user.Email}, delOpts...); err != nil {
		s.Logr.Error().Err(err).Msgf("Verify.redis.Del.Failed")
	}

	// send email: email successfully verified
	opts := []asynq.Option{asynq.MaxRetry(3), asynq.Group(worker.QUEUE_LOW), asynq.ProcessIn(time.Second * 5)}
	if err = s.taskDistributor.DistributeTaskSendEmailVerified(ctx, worker.PayloadSendEmailVerified{Email: user.Email}, opts...); err != nil {
		s.Logr.Error().Err(err).Msg("Verify.DistributeTaskSendEmailVerified.Error")
	}

	return &rpc.VerifyResponse{User: publicProfile(user)}, nil
}

func unique_violation(err *pq.Error) string {
	s := strings.Split(err.Detail, "=")[0]
	return strings.Split(strings.Split(s, "(")[1], ")")[0]
}

func validateVerifyRequest(req *rpc.VerifyRequest) (violations []*errdetails.BadRequest_FieldViolation) {
	if err := validator.ValidateEmail(req.GetEmail()); err != nil {
		violations = append(violations, fieldViolation("email", err))
	}
	if len(req.GetCode()) != 20 {
		// our code is always unqiue 20char long generated by utils.UUID_XID()
		violations = append(violations, fieldViolation("code", fmt.Errorf("invalid code")))
	}
	return
}
