// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.15.8
// source: rpc-recovery.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecoveryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	LogoutAll bool   `protobuf:"varint,3,opt,name=logout_all,json=logoutAll,proto3" json:"logout_all,omitempty"`
}

func (x *RecoveryRequest) Reset() {
	*x = RecoveryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_recovery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryRequest) ProtoMessage() {}

func (x *RecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_recovery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryRequest.ProtoReflect.Descriptor instead.
func (*RecoveryRequest) Descriptor() ([]byte, []int) {
	return file_rpc_recovery_proto_rawDescGZIP(), []int{0}
}

func (x *RecoveryRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RecoveryRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RecoveryRequest) GetLogoutAll() bool {
	if x != nil {
		return x.LogoutAll
	}
	return false
}

type RecoveryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RecoveryResponse) Reset() {
	*x = RecoveryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_recovery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryResponse) ProtoMessage() {}

func (x *RecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_recovery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryResponse.ProtoReflect.Descriptor instead.
func (*RecoveryResponse) Descriptor() ([]byte, []int) {
	return file_rpc_recovery_proto_rawDescGZIP(), []int{1}
}

func (x *RecoveryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_recovery_proto protoreflect.FileDescriptor

var file_rpc_recovery_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x70, 0x63, 0x2d, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x72, 0x75, 0x65, 0x61, 0x75, 0x74, 0x68, 0x22, 0x5a,
	0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x41, 0x6c, 0x6c, 0x22, 0x2c, 0x0a, 0x10, 0x52, 0x65,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x72, 0x6a, 0x61, 0x67, 0x65, 0x72, 0x2f,
	0x74, 0x72, 0x75, 0x65, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_recovery_proto_rawDescOnce sync.Once
	file_rpc_recovery_proto_rawDescData = file_rpc_recovery_proto_rawDesc
)

func file_rpc_recovery_proto_rawDescGZIP() []byte {
	file_rpc_recovery_proto_rawDescOnce.Do(func() {
		file_rpc_recovery_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_recovery_proto_rawDescData)
	})
	return file_rpc_recovery_proto_rawDescData
}

var file_rpc_recovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_recovery_proto_goTypes = []interface{}{
	(*RecoveryRequest)(nil),  // 0: trueauth.RecoveryRequest
	(*RecoveryResponse)(nil), // 1: trueauth.RecoveryResponse
}
var file_rpc_recovery_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_recovery_proto_init() }
func file_rpc_recovery_proto_init() {
	if File_rpc_recovery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_recovery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoveryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_recovery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoveryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_recovery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_recovery_proto_goTypes,
		DependencyIndexes: file_rpc_recovery_proto_depIdxs,
		MessageInfos:      file_rpc_recovery_proto_msgTypes,
	}.Build()
	File_rpc_recovery_proto = out.File
	file_rpc_recovery_proto_rawDesc = nil
	file_rpc_recovery_proto_goTypes = nil
	file_rpc_recovery_proto_depIdxs = nil
}
